runtime: php81

entrypoint: serve front-controller.php

handlers:
# Serve assets as static resources.
- url: /css
  static_dir: css
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /data
  static_dir: data
  secure: always

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# Serve php scripts.
- url: /.*
  script: auto
  secure: always

