runtime: php55
api_version: 1
automatic_scaling:

handlers:
# Serve assets as static resources.
- url: /css
  static_dir: css
  secure: always
  application_readable: true

- url: /img
  static_dir: img
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /data
  static_dir: data
  secure: always
  application_readable: true

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# Dont serve internal files
- url: /(master|default_vars|.*_content|.*_controller|.*_head)(\.(php|html))?
  script: 404.php

# Serve php scripts.
- url: /
  script: index.php
  secure: always

- url: /(index|classes|venues|events|gallery|contact)(\.html)?$
  script: \1.php
  secure: always

- url: /.*
  script: 404.php

