runtime: php55
api_version: 1

automatic_scaling:

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /dancextremeadmin.js
  static_files: static/dancextremeadmin.js
  upload: static/dancextremeadmin.js

- url: /update_venue.php
  script: update_venue.php

- url: /update_gallery.php
  script: update_gallery.php

- url: /update_holiday_gallery.php
  script: update_holiday_gallery.php

skip_files:
- node_modules/
- package.*
- app.js
- cors*  

