runtime: php81

entrypoint: serve front-controller.php

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /dancextremeadmin.js
  static_files: static/dancextremeadmin.js
  upload: static/dancextremeadmin.js

- url: /.*
  script: auto


